clear;
clc;
run('vlfeat/toolbox/vl_setup');
plastic1 = imread('../data/plastic1.png');
plastic2 = imread('../data/plastic2.png');
plastic1_disp = imread('../data/plastic1_disp.png');
plastic2_disp = imread('../data/plastic2_disp.png');
plastic1_gray_sp = im2single(rgb2gray(plastic1));
plastic2_gray_sp = im2single(rgb2gray(plastic2));
[F1,D1] = vl_sift(plastic1_gray_sp);
F1 = F1';
D1 = D1';
[F2,D2] = vl_sift(plastic2_gray_sp);
F2 = F2';
D2 = D2';
sift_matching_threshold = 7;
[matching_idx1, matching_idx2] = sift_matching(D1,D2,sift_matching_threshold);
matching_points1 = F1(matching_idx1, 1:2);
[~,IA,~] = unique(matching_points1, 'rows');
matching_points1 = matching_points1(IA, :);
matching_points2 = F2(matching_idx2, 1:2);
matching_points2 = matching_points2(IA, :);
clear F1 F2 D1 D2 IA;
[h, idx] = ransac_homography(matching_points1, matching_points2, 100, 0.4, 3000, 50, 0.5);
rectified_img = rectification(h, plastic1);
imshow(rectified_img);